export interface Webhooks {
  id: number
  name: string
  destination_url: string
  token: string
  status: string
  events: string[]
  createdAt: string
  updatedAt: string
}

export interface SentWebhooks {
  attempt: number
  destination_url: string
  status: string
  status_code: number
  payload: Record<string, string>
  sent_date: Date
}

export enum WebhookAvailableEvent {
  CHARGE_CREATED = 'CHARGE_CREATED',
  CHARGE_AUTHORIZED = 'CHARGE_AUTHORIZED',
  CHARGE_PAID = 'CHARGE_PAID',
  CHARGE_UPDATED = 'CHARGE_UPDATED',
  CHARGE_OVERDUE = 'CHARGE_OVERDUE',
  CHARGE_IN_ANALYSIS = 'CHARGE_IN_ANALYSIS',
  CHARGE_DECLINED = 'CHARGE_DECLINED',
  CHARGE_CANCELED = 'CHARGE_CANCELED',
  CHARGE_AWAITING = 'CHARGE_AWAITING',
  CHARGE_REFUNDED = 'CHARGE_REFUNDED',
  RECURRENCE_INITIAL = 'RECURRENCE_INITIAL',
  RECURRENCE_AUTHORIZED = 'RECURRENCE_AUTHORIZED',
  RECURRENCE_IN_ANALYSIS = 'RECURRENCE_IN_ANALYSIS',
  RECURRENCE_REFUNDED = 'RECURRENCE_REFUNDED',
  RECURRENCE_AWAITING = 'RECURRENCE_AWAITING',
  RECURRENCE_UPDATED = 'RECURRENCE_UPDATED',
  RECURRENCE_ACTIVATED = 'RECURRENCE_ACTIVATED',
  RECURRENCE_SUSPENDED = 'RECURRENCE_SUSPENDED',
  RECURRENCE_CHARGED = 'RECURRENCE_CHARGED',
  RECURRENCE_OVERDUE = 'RECURRENCE_OVERDUE',
  RECURRENCE_EXPIRED = 'RECURRENCE_EXPIRED',
  RECURRENCE_CANCELED = 'RECURRENCE_CANCELED',
  RECURRENCE_MIGRATED = 'RECURRENCE_MIGRATED',
  TRANSFER_CREATED = 'TRANSFER_CREATED',
  TRANSFER_DONE = 'TRANSFER_DONE',
  TRANSFER_IN_BANK_PROCESSING = 'TRANSFER_IN_BANK_PROCESSING',
  TRANSFER_CANCELLED = 'TRANSFER_CANCELLED',
  TRANSFER_PENDING = 'TRANSFER_PENDING',
  TRANSFER_BLOCKED = 'TRANSFER_BLOCKED',
  TRANSFER_FAILED = 'TRANSFER_FAILED',
}

export enum WebhookChargeEvent {
  CHARGE_CREATED = 'CHARGE_CREATED',
  CHARGE_AUTHORIZED = 'CHARGE_AUTHORIZED',
  CHARGE_PAID = 'CHARGE_PAID',
  CHARGE_UPDATED = 'CHARGE_UPDATED',
  CHARGE_OVERDUE = 'CHARGE_OVERDUE',
  CHARGE_IN_ANALYSIS = 'CHARGE_IN_ANALYSIS',
  CHARGE_DECLINED = 'CHARGE_DECLINED',
  CHARGE_CANCELED = 'CHARGE_CANCELED',
  CHARGE_AWAITING = 'CHARGE_AWAITING',
  CHARGE_REFUNDED = 'CHARGE_REFUNDED',
}

export enum WebhookRecurrenceEvent {
  RECURRENCE_INITIAL = 'RECURRENCE_INITIAL',
  RECURRENCE_AUTHORIZED = 'RECURRENCE_AUTHORIZED',
  RECURRENCE_IN_ANALYSIS = 'RECURRENCE_IN_ANALYSIS',
  RECURRENCE_REFUNDED = 'RECURRENCE_REFUNDED',
  RECURRENCE_AWAITING = 'RECURRENCE_AWAITING',
  RECURRENCE_UPDATED = 'RECURRENCE_UPDATED',
  RECURRENCE_ACTIVATED = 'RECURRENCE_ACTIVATED',
  RECURRENCE_SUSPENDED = 'RECURRENCE_SUSPENDED',
  RECURRENCE_CHARGED = 'RECURRENCE_CHARGED',
  RECURRENCE_OVERDUE = 'RECURRENCE_OVERDUE',
  RECURRENCE_EXPIRED = 'RECURRENCE_EXPIRED',
  RECURRENCE_CANCELED = 'RECURRENCE_CANCELED',
  RECURRENCE_MIGRATED = 'RECURRENCE_MIGRATED',
}

export enum WebhookTransferEvent {
  TRANSFER_CREATED = 'TRANSFER_CREATED',
  TRANSFER_DONE = 'TRANSFER_DONE',
  TRANSFER_IN_BANK_PROCESSING = 'TRANSFER_IN_BANK_PROCESSING',
  TRANSFER_CANCELLED = 'TRANSFER_CANCELLED',
  TRANSFER_PENDING = 'TRANSFER_PENDING',
  TRANSFER_BLOCKED = 'TRANSFER_BLOCKED',
  TRANSFER_FAILED = 'TRANSFER_FAILED',
}

export enum WebhookTemplateStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}
