export interface Webhooks {
  id: number
  name: string
  destinationUrl: string
  token: string
  status: string
  events: string[]
  createdAt: string
  updatedAt: string
}

export enum WebhookAvailableEvent {
  CHARGE_CREATED = 'CHARGE_CREATED',
  CHARGE_AUTHORIZED = 'CHARGE_AUTHORIZED',
  CHARGE_PAID = 'CHARGE_PAID',
  CHARGE_UPDATED = 'CHARGE_UPDATED',
  CHARGE_OVERDUE = 'CHARGE_OVERDUE',
  CHARGE_IN_ANALYSIS = 'CHARGE_IN_ANALYSIS',
  CHARGE_DECLINED = 'CHARGE_DECLINED',
  CHARGE_CANCELED = 'CHARGE_CANCELED',
  CHARGE_AWAITING = 'CHARGE_AWAITING',
  CHARGE_REFUNDED = 'CHARGE_REFUNDED',
  RECURRENCE_INITIAL = 'RECURRENCE_INITIAL',
  RECURRENCE_AUTHORIZED = 'RECURRENCE_AUTHORIZED',
  RECURRENCE_IN_ANALYSIS = 'RECURRENCE_IN_ANALYSIS',
  RECURRENCE_REFUNDED = 'RECURRENCE_REFUNDED',
  RECURRENCE_AWAITING = 'RECURRENCE_AWAITING',
  RECURRENCE_UPDATED = 'RECURRENCE_UPDATED',
  RECURRENCE_ACTIVATED = 'RECURRENCE_ACTIVATED',
  RECURRENCE_SUSPENDED = 'RECURRENCE_SUSPENDED',
  RECURRENCE_CHARGED = 'RECURRENCE_CHARGED',
  RECURRENCE_OVERDUE = 'RECURRENCE_OVERDUE',
  RECURRENCE_EXPIRED = 'RECURRENCE_EXPIRED',
  RECURRENCE_CANCELED = 'RECURRENCE_CANCELED',
  RECURRENCE_MIGRATED = 'RECURRENCE_MIGRATED',
}

export enum WebhookChargeEvent {
  CHARGE_CREATED = 'CHARGE_CREATED',
  CHARGE_AUTHORIZED = 'CHARGE_AUTHORIZED',
  CHARGE_PAID = 'CHARGE_PAID',
  CHARGE_UPDATED = 'CHARGE_UPDATED',
  CHARGE_OVERDUE = 'CHARGE_OVERDUE',
  CHARGE_IN_ANALYSIS = 'CHARGE_IN_ANALYSIS',
  CHARGE_DECLINED = 'CHARGE_DECLINED',
  CHARGE_CANCELED = 'CHARGE_CANCELED',
  CHARGE_AWAITING = 'CHARGE_AWAITING',
  CHARGE_REFUNDED = 'CHARGE_REFUNDED',
}

export enum WebhookRecurrenceEvent {
  RECURRENCE_INITIAL = 'RECURRENCE_INITIAL',
  RECURRENCE_AUTHORIZED = 'RECURRENCE_AUTHORIZED',
  RECURRENCE_IN_ANALYSIS = 'RECURRENCE_IN_ANALYSIS',
  RECURRENCE_REFUNDED = 'RECURRENCE_REFUNDED',
  RECURRENCE_AWAITING = 'RECURRENCE_AWAITING',
  RECURRENCE_UPDATED = 'RECURRENCE_UPDATED',
  RECURRENCE_ACTIVATED = 'RECURRENCE_ACTIVATED',
  RECURRENCE_SUSPENDED = 'RECURRENCE_SUSPENDED',
  RECURRENCE_CHARGED = 'RECURRENCE_CHARGED',
  RECURRENCE_OVERDUE = 'RECURRENCE_OVERDUE',
  RECURRENCE_EXPIRED = 'RECURRENCE_EXPIRED',
  RECURRENCE_CANCELED = 'RECURRENCE_CANCELED',
  RECURRENCE_MIGRATED = 'RECURRENCE_MIGRATED',
}

export enum WebhookTemplateStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}
